version: '2'
services:
  frontend:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - './guestbook-simple-frontend/src/main/html:/etc/nginx/html:ro'
      - >-
        ./guestbook-simple-frontend/src/main/config/nginx-base.conf:/etc/nginx/nginx.conf:ro
  gateway:
    image: 'looztra/guestbook-gateway:0.6.1-aio'
    ports:
      - '8080:8080'
    environment:
      GATEWAY_GUESTBOOK_ENDPOINTSASSTRING: 'storage:8080'
      GATEWAY_FILTER_ENDPOINTSASSTRING: 'filter:8080'
    depends_on:
      - storage
      - filter
  storage:
    image: 'looztra/guestbook-storage:0.6.1-aio'
    ports:
      - '8085:8080'
    environment:
      GUESTBOOK_BACKEND_REDIS_READ_VIP: redis
      GUESTBOOK_BACKEND_REDIS_WRITE_VIP: redis
    depends_on:
      - redis
  filter:
    image: 'looztra/guestbook-filter:0.6.1-aio'
    ports:
      - '8086:8080'
  redis:
    image: 'redis:3-alpine'
