version: '3'
services:
  frontend:
    image: looztra/guestbook-frontend:0.6.3-aio
    ports:
      - "8000:80"
    networks:
      front:
  gateway:
    image: looztra/guestbook-gateway:0.6.3-aio
    ports:
      - "8080:8080"
    environment:
      GATEWAY_GUESTBOOK_ENDPOINTSASSTRING: "storage:8080"
      GATEWAY_FILTER_ENDPOINTSASSTRING: "filter:8080"
      MANAGEMENT_SECURITY_ENABLED: "false"
    depends_on:
      - storage
      - filter
    networks:
      front:
      middle:
  storage:
    image: looztra/guestbook-storage:0.6.3-aio
    ports:
      - "8085:8080"
    environment:
      GUESTBOOK_BACKEND_REDIS_READ_VIP: redis
      GUESTBOOK_BACKEND_REDIS_WRITE_VIP: redis
      MANAGEMENT_SECURITY_ENABLED: "false"
    depends_on:
      - redis
    networks:
      middle:
      back:
  filter:
    image: looztra/guestbook-filter:0.6.3-aio
    ports:
      - "8086:8080"
    environment:
      MANAGEMENT_SECURITY_ENABLED: "false"
    networks:
      middle:
  redis:
    image: redis:3-alpine
    networks:
      back:

networks:
  front:
  middle:
  back:
